name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build_and_publish_image_in_dockerhub:
    runs-on: ubuntu-latest
    name   : Build image and push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker login -u ${{ secret.DOCKER_USERNAME}} -p ${{ secret.DOCKER_PASSWORD}}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: |
        docker build --file Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/api-flask-vivek:${{github.ref_name}} .
    
    - name: Push Docker image to DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/api-flask-vivek:${{github.ref_name}}

    - name: Run Flask application in Docker container
      run: |
        docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/api-flask-vivek:${{github.ref_name}}
